db:
  image: postgres
  ports:
    - "5432"

# redis:
#   image: mini/redis
#   ports:
#     - "6379"

web:
  build: .
  command: foreman start
  volumes:
    - .:/appror
  ports:
    - "3000:3000"
  links:
    - db
#    - redis




# Instructions

# - first build
# docker-compose run web

# - or run and create new rails application in current dir
# docker-compose run web rails new . --force --database=postgresql --skip-bundle

# - update image after changes
# docker-compose build

# - launch stack
# docker-compose up

# - create database
# docker-compose run web rake db:create

# and so on
# docker-compose stop
# docker-compose start
# docker-compose logs
